# Generated by Django 4.2.17 on 2025-01-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('CANCELED', 'Canceled')], default='VALID', max_length=20),
        ),
    ]
